//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

#pragma mark Typedef'd Structures

typedef struct {
    long long _field1;
    long long _field2;
} CDStruct_912cb5d2;

#pragma mark -

@class IMKTextReplacementController, IMKTextReplacementEntryContext, IMKTextReplacementEntry,
IMKTextReplacementControllerContext, IMKTextReplacementEntryTransaction, IMKTextReplacementEntryTransactionContext;

//
// File: /System/Library/Frameworks/InputMethodKit.framework/Versions/A/InputMethodKit
// UUID: 1EF5BA7B-EF17-3FF0-877E-A8A1AED702AF
//
//                           Arch: x86_64
//                Current version: 1.0.0
//          Compatibility version: 1.0.0
//                 Source version: 260.0.0.0.0
//       Minimum Mac OS X version: 10.11.0
//                    SDK version: 10.11.0
//
// Objective-C Garbage Collection: Supported
//

@interface IMKTextReplacementEntryContext : NSObject <NSSecureCoding>
{
    NSString *_phrase;
    NSString *_shortcut;
    NSNumber *_timestamp;
}

+ (BOOL)supportsSecureCoding;
@property(retain) NSNumber *timestamp; // @synthesize timestamp=_timestamp;
@property(copy) NSString *shortcut; // @synthesize shortcut=_shortcut;
@property(copy) NSString *phrase; // @synthesize phrase=_phrase;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

@interface IMKTextReplacementEntry : NSObject <NSSecureCoding, NSCopying>

+ (id)entryWithPhrase:(id)arg1 shortcut:(id)arg2 timestamp:(id)arg3;
+ (BOOL)supportsSecureCoding;
@property(retain) IMKTextReplacementEntryContext *context; // @synthesize context=_context;
- (long long)validate;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
@property(readonly, retain) NSNumber *timestamp;
@property(readonly, copy) NSString *phrase;
@property(readonly, copy) NSString *shortcut;
- (void)dealloc;
- (id)initWithPhrase:(id)arg1 shortcut:(id)arg2 timestamp:(id)arg3;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

@interface IMKTextReplacementControllerContext : NSObject

@property(retain) NSXPCConnection *connection; // @synthesize connection=_connection;
@property(retain) IMKTextReplacementController *controller; // @synthesize controller=_controller;
@property(copy) CDUnknownBlockType phraseShortcutPairsDidChangeHandler; // @synthesize phraseShortcutPairsDidChangeHandler=_phraseShortcutPairsDidChangeHandler;
@property(copy) CDUnknownBlockType entriesDidChangeHandler; // @synthesize entriesDidChangeHandler=_entriesDidChangeHandler;
- (void)dealloc;
- (id)initWithController:(id)arg1;
- (id)init;

@end

@interface IMKTextReplacementController : NSObject

@property(retain) IMKTextReplacementControllerContext *context; // @synthesize context=_context;
- (id)convertToPhraseShortcutPairs:(id)arg1;
- (id)convertPhraseShortcutPairs:(id)arg1;
- (void)entriesDidChange:(id)arg1;
- (void)cancelPendingTransactions;
- (void)performTransactions:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
@property(copy) CDUnknownBlockType phraseShortcutPairsDidChangeHandler;
@property(copy) CDUnknownBlockType entriesDidChangeHandler;
@property(readonly, copy) NSArray *phraseShortcutPairs;
@property(readonly, copy) NSArray *entries;
- (void)dealloc;
- (id)init;

@end

@interface IMKTextReplacementEntryTransactionContext : NSObject <NSSecureCoding>

+ (BOOL)supportsSecureCoding;
@property(retain) IMKTextReplacementEntry *succeedEntry; // @synthesize succeedEntry=_succeedEntry;
@property(retain) IMKTextReplacementEntry *existingEntry; // @synthesize existingEntry=_existingEntry;
@property long long transactionType; // @synthesize transactionType=_transactionType;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

@interface IMKTextReplacementEntryTransaction : NSObject <NSSecureCoding>

+ (id)entryToUpdate:(id)arg1 withEntryToSet:(id)arg2;
+ (id)entryToInsert:(id)arg1;
+ (id)entryToDelete:(id)arg1;
+ (BOOL)supportsSecureCoding;
@property(retain) IMKTextReplacementEntryTransactionContext *context; // @synthesize context=_context;
- (id)succeedEntry;
- (id)existingEntry;
@property(readonly) long long transactionType;
- (void)dealloc;
- (id)initWithExistingEntry:(id)arg1 succeedEntry:(id)arg2;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end
