//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown
typedef void (^_KSTextReplacementTranscationHandler)(NSError *error);

#pragma mark -

//
// File: /System/Library/PrivateFrameworks/KeyboardServices.framework/Versions/A/KeyboardServices
// UUID: FE07C1F1-8B0D-3379-A7B4-76E730F5F0A2
//
//                           Arch: x86_64
//                Current version: 1.0.0
//          Compatibility version: 1.0.0
//                 Source version: 56.0.0.0.0
//       Minimum Mac OS X version: 10.12.0
//                    SDK version: 10.12.0
//
// Objective-C Garbage Collection: Unsupported
//

@protocol _KSTextReplacementCancellation <NSObject>
- (void)cancelPendingUpdates;
@end

@protocol _KSTextReplacementServiceProtocol <NSObject>
- (void)queryTextReplacementsWithPredicate:(NSPredicate *)arg1 reply:(void (^)(NSArray *, BOOL))arg2;
- (void)queryTextReplacementEntriesWithReply:(void (^)(NSArray *, BOOL))arg1;
- (void)cancelPendingUpdatesWithReply:(void (^)(BOOL, NSError *))arg1;
- (void)requestSyncWithReply:(void (^)(BOOL))arg1;
- (void)removeAllEntries;
- (void)addEntries:(NSArray *)arg1 removeEntries:(NSArray *)arg2 withReply:(void (^)(BOOL, NSError *))arg3;
@end

@protocol _KSTextReplacementStoreProtocol <NSObject>
- (void)requestSyncWithCompletionBlock:(void (^)(BOOL))arg1;
- (void)queryTextReplacementsWithPredicate:(NSPredicate *)arg1 callback:(void (^)(NSArray *, BOOL))arg2;
- (void)queryTextReplacementsWithCallback:(void (^)(NSArray *, BOOL))arg1;
- (NSArray *)textReplacementEntries;
- (void)removeAllEntries;
- (void)addEntries:(NSArray *)arg1 removeEntries:(NSArray *)arg2 withCompletionHandler:(void (^)(NSError *))arg3;
@end

@class _KSTextReplacementEntry;


@interface _KSTextReplacementClientStore : NSObject <_KSTextReplacementStoreProtocol, _KSTextReplacementCancellation>

- (id)phraseShortcuts;
- (void)performTransaction:(id)arg1 completionHandler:(_KSTextReplacementTranscationHandler)arg2;
- (NSArray <_KSTextReplacementEntry *> *)textReplacementEntries;
- (void)modifyEntry:(id)arg1 toEntry:(id)arg2 withCompletionHandler:(_KSTextReplacementTranscationHandler)arg3;
- (id)init;

@end


@interface _KSTextReplacementEntry : NSObject <NSSecureCoding, NSCopying>
{
    BOOL _needsSaveToCloud;
    BOOL _wasDeleted;
    NSString *_phrase;
    NSString *_shortcut;
    NSDate *_timestamp;
    _KSTextReplacementEntry *_priorValue;
    NSData *_cloudData;
    NSString *_cloudID;
}

+ (id)localEntryFromCloudEntry:(id)arg1;
+ (BOOL)supportsSecureCoding;
@property(copy, nonatomic) NSString *cloudID; // @synthesize cloudID=_cloudID;
@property BOOL wasDeleted; // @synthesize wasDeleted=_wasDeleted;
@property BOOL needsSaveToCloud; // @synthesize needsSaveToCloud=_needsSaveToCloud;
@property(retain, nonatomic) NSData *cloudData; // @synthesize cloudData=_cloudData;
@property(retain, nonatomic) _KSTextReplacementEntry *priorValue; // @synthesize priorValue=_priorValue;
@property(copy, nonatomic) NSDate *timestamp; // @synthesize timestamp=_timestamp;
@property(copy, nonatomic) NSString *shortcut; // @synthesize shortcut=_shortcut;
@property(copy, nonatomic) NSString *phrase; // @synthesize phrase=_phrase;
- (BOOL)isEquivalentTo:(id)arg1;
- (id)description;
- (id)attributesDict;
- (id)uniqueID;
- (id)uniqueRecordName;
- (id)uniqueRecordNameVer0;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end


@interface _KSTextReplacementHelper : NSObject

+ (id)fetchConfigurationPlist;
+ (id)sampleShortcut;
+ (id)appleLanguagesPreference;
+ (id)aggdPrefix;
+ (void)logPhraseWordCount:(long long)arg1;
+ (void)extractAggdMetricsForTextReplacement:(id)arg1;
+ (id)multipleAddErrors:(id)arg1 removeErrors:(id)arg2;
+ (id)errorWithCode:(long long)arg1 failedAdds:(id)arg2 failedDeletes:(id)arg3;
+ (id)errorWithCode:(long long)arg1 forEntry:(id)arg2;
+ (long long)validateTextReplacement:(id)arg1;
+ (id)transactionFromTextReplacementEntry:(id)arg1 forDelete:(BOOL)arg2;
+ (id)textReplaceEntryFromTIDictionaryValue:(id)arg1;
+ (NSString *)errorStringForCode:(long long)arg1;

@end

