//
//  shortcuts.h
//  shortcuts
//
//  Created by Dmitry Rodionov on 21/08/16.
//  Copyright © 2016 Internals Exposed. All rights reserved.
//

@import Foundation;

/// List existing text replacements. You can also specify the desired output format.
int list(NSString * _Nullable mode);

/// Import text replacement from a property list file generated by Keyboard Preferences Pane
/// (see https://support.apple.com/en-au/HT204006 for details).
/// The default conflict resolution strategy is that the existing entries will not be overwritten
/// with those from the input file. You can alter this behaviour by setting allowOverwrites to YES.
int import(NSString * _Nonnull inputPropertyListPath, BOOL allowOverwrites);

/// Create a new text replacement that expands <shortcut> to <phrase>.
/// The conflict resolution strategy is conservative: you should set allowOverwrites to YES to allow
/// updating existing entries (with the same <shortcut>).
int new(NSString * _Nonnull shortcut, NSString * _Nonnull phrase, BOOL allowOverwrites);

/// Update an existing entry for the same <shortcut> or creates a new one if such entry
/// doesn't exist yet. This is an alias for new(shortcut, phrase, /* force */YES);
int update(NSString * _Nonnull shortcut, NSString * _Nonnull phrase);

/// Delete the specified shortcut (if any).
int delete(NSString * _Nonnull shortcut);
